### PR TITLE
iterators for the Vector class

### PR DESCRIPTION
**Pull request by Boiethios**
That should be good ;)

### CODE REVIEW

**Comment by jube** [comment]
IMO, no need for a typedef, a pointer is an iterator, so `begin()` and `end()` should return a pointer. This will make the code much simpler.

**Comment by jube** [comment]
Ho and I forgot: can you do this relative to the `develop` branch? I think I should add something in the guidelines :)

**Comment by Boiethios** [comment]
Ok, so we cancel this pull request and I open another in the `develop` branch ?

**Comment by jube** [comment]
Don't worry, I will be able to merge your branch in the develop branch. Go on.

**Comment by jube** [comment]
It has been merged into `develop`. Thanks!

**Pull request merged**
