### PR TITLE
[Widgets] Writing a basic widget system

### PR DESCRIPTION
**Pull request by Xeryko**
It's a proposal to the Issue #16 

I know this code isn't perfect but it's a start.

The Widget State contains only 3 state (none, disabled and selected) because the hover state can be assign to a selected state and the active state is about instantaneous.

Maybe the hover state should come back to apply special effects to the widget when the mouse is hover....

I moved for now the handler into the Widget class but it should be modified later.
Moreover, the action in the ActivableWidget isn't used at all for now.

For the WidgetContainer part, i used functions to select the widget in the list. the power of action isn't used for now. It won't free the widgets in the list for now.

I will have to work for my studies projects so I think I won't work on it for now.

### CODE REVIEW

**Comment by jube** [comment]
TODO (may be incomplete):

- global changes
  - remove ActivableWidget (yes, Action is not used and useless)
  - put all subclasses of Widget in Widgets.h/Widgets.cc files (like Activities, Shapes, Curves, Views, Controls, etc)
  - problems with global bounds computations (local bounds can not be global bounds)
  - lack of license headers (with your name)
  - add yourself in AUTHORS.md (in the contributors list)
- specific changes
  - in Widget and WidgetState, replace None by Default
  - in TextButtonWidget, is there a relation between rectangle position and text position?
  - in WidgetContainer: no delete! the user is responsible for the lifetime of the widget!
  - in WidgetContainer: take a reference instead of a pointer in `addWidget()` (like `addEntity()`, etc)
  - in WidgetContainer: do we need a view?

**Comment by Xeryko** [comment]
Here is the list of work done :
* global changes
  * [x] remove ActivableWidget
  * [x] put all subclasses of Widget in Widgets.h/Widgets.cc files
  * [ ] problems with global bounds computations (working on it....)
  * [x] lack of license headers
  * [x] add yourself in AUTHORS.md
  * [x] add GF_API
  * [ ] add an example (will come later)
* specific changes
  * [x] in Widget and WidgetState, replace None by Default
  * [x] in TextButtonWidget, is there a relation between rectangle position and text position? (now yes...)
  * [x] in WidgetContainer: no delete! the user is responsible for the lifetime of the widget!
  * [x] in WidgetContainer: take a reference instead of a pointer in addWidget() (like addEntity(), etc)
  * [x] in WidgetContainer: do we need a view?

I purpose this basic solution for now and missing things will come later

**Comment by jube** [comment]
Don't worry for the failed build, it's an appveyor problem ;)

**Comment by jube** [comment]
"put all *subclasses* of Widget in Widgets.h/Widgets.cc files"
gf::Widget in Widget.h/cc and all other in Widgets.h/cc ;)

**Comment by Xeryko** [comment]
Sorry, I failed adding the removed files,
Do you want that i squash my commits?

**Comment by jube** [comment]
As you want... as long as it's not merged, you can do what you want ;)

**Pull request merged**
